from app.application.use_cases.conversation.graph import build_conversation_graph
from app.config.settings import MAX_TOOL_ITERATIONS
from tests.application.use_cases.conversation.fakes import (
    FakeCannedReplyConfig,
    FakeCheckBusinessAvailability,
    FakeConversationHistory,
    FakeLLM,
    FakePromptConfig,
    FakeReplyLanguageEnforcer,
    FakeReplyLanguageResolver,
    FakeRetrievalTools,
    FakeTranslation,
)


def _tool_call_response(intent: str, call_id="c1"):
    return {"content": None, "tool_calls": [{"id": call_id, "name": "classify_intent", "arguments": {"intent": intent}}]}


def _build_graph(*, llm, check_available=True, retrieval_call_result=None, conversation_history=None):
    return build_conversation_graph(
        llm=llm,
        conversation_history=conversation_history or FakeConversationHistory(),
        reply_language_resolver=FakeReplyLanguageResolver(),
        reply_language_enforcer=FakeReplyLanguageEnforcer(),
        translation=FakeTranslation(),
        prompt_config=FakePromptConfig(),
        retrieval_tools=FakeRetrievalTools(call_result=retrieval_call_result),
        check_business_availability=FakeCheckBusinessAvailability(check_available),
        advisor_available_reply_config=FakeCannedReplyConfig("habla con un asesor"),
        agenda_reply_config=FakeCannedReplyConfig("agenda aqui"),
        flow_confirmation_reply_config=FakeCannedReplyConfig("confirma tus datos"),
        max_history=6,
    )


def _initial_state(question="hola"):
    return {
        "tenant_id": "agb",
        "session_id": "s1",
        "channel": "website",
        "user_question": question,
        "visitor_language": None,
    }


async def test_route_retrieval_without_tool_calls():
    # generate_with_tools already produced the real, complete answer here (no
    # tool_calls requested) -- must be used as-is via use_existing_answer,
    # NOT discarded and regenerated by a second (generate_final) LLM call.
    # This exact discard-and-regenerate bug is what shipped and was found via
    # a live test 2026-09-19/20 (see route_after_generate's docstring).
    llm = FakeLLM(
        [
            _tool_call_response("info_general"),
            {"content": "respuesta final", "tool_calls": None},  # generate_with_tools
        ]
    )
    graph = _build_graph(llm=llm)

    result = await graph.ainvoke(_initial_state())

    assert result["route"] == "retrieval"
    assert result["final_answer"] == "respuesta final"
    assert len(llm.calls) == 2


async def test_route_retrieval_with_one_tool_call():
    llm = FakeLLM(
        [
            _tool_call_response("info_general"),
            {
                "content": None,
                "tool_calls": [{"id": "t1", "name": "search_price_catalog", "arguments": {"query": "nariz"}}],
            },
            # After the tool result, the model answers directly with no more
            # tool_calls -- this real content must be used as-is (no second,
            # generate_final call).
            {"content": "el precio es 5000 euros", "tool_calls": None},
        ]
    )
    graph = _build_graph(llm=llm, retrieval_call_result=[{"procedure_name": "RINOPLASTIA", "price_range_eur": "5000"}])

    result = await graph.ainvoke(_initial_state("cuanto cuesta la rinoplastia"))

    assert result["route"] == "retrieval"
    assert result["final_answer"] == "el precio es 5000 euros"
    assert len(llm.calls) == 3
    # Tool result message made it into the running message list.
    tool_messages = [m for m in result["messages"] if m.get("role") == "tool"]
    assert len(tool_messages) == 1
    assert "RINOPLASTIA" in tool_messages[0]["content"]


async def test_route_retrieval_forces_generate_final_when_iteration_budget_is_spent():
    # Unlike the tests above, the model keeps requesting tool calls forever
    # here -- once tool_call_count reaches MAX_TOOL_ITERATIONS, the loop must
    # stop and force a real generate_final call (tool_choice="none") instead
    # of looping indefinitely or silently returning an empty answer.
    completions = [_tool_call_response("info_general")]
    for _ in range(MAX_TOOL_ITERATIONS):
        completions.append(
            {
                "content": None,
                "tool_calls": [{"id": "t1", "name": "search_price_catalog", "arguments": {"query": "nariz"}}],
            }
        )
    completions.append({"content": "respuesta forzada", "tool_calls": None})  # generate_final
    llm = FakeLLM(completions)
    graph = _build_graph(llm=llm, retrieval_call_result=[{"procedure_name": "RINOPLASTIA", "price_range_eur": "5000"}])

    result = await graph.ainvoke(_initial_state("cuanto cuesta la rinoplastia"))

    assert result["route"] == "retrieval"
    assert result["final_answer"] == "respuesta forzada"
    assert result["tool_call_count"] == MAX_TOOL_ITERATIONS
    # orchestrator + MAX_TOOL_ITERATIONS generate_with_tools calls + 1 generate_final
    assert len(llm.calls) == MAX_TOOL_ITERATIONS + 2


async def test_route_agenda():
    llm = FakeLLM([_tool_call_response("agendar_cita")])
    graph = _build_graph(llm=llm)

    result = await graph.ainvoke(_initial_state("quiero agendar una cita"))

    assert result["route"] == "agenda"
    assert result["final_answer"] == "agenda aqui"
    assert len(llm.calls) == 1


async def test_route_direct_when_advisor_available():
    llm = FakeLLM([_tool_call_response("hablar_con_asesor")])
    graph = _build_graph(llm=llm, check_available=True)

    result = await graph.ainvoke(_initial_state("quiero hablar con un asesor"))

    assert result["route"] == "direct"
    assert result["final_answer"] == "habla con un asesor"


async def test_route_flow_when_advisor_unavailable():
    llm = FakeLLM([_tool_call_response("hablar_con_asesor")])
    graph = _build_graph(llm=llm, check_available=False)

    result = await graph.ainvoke(_initial_state("quiero hablar con un asesor"))

    assert result["route"] == "flow"
    assert result["final_answer"] == "confirma tus datos"
    # No history yet -- must not call the LLM at all, just the canned reply.
    assert len(llm.calls) == 1


async def test_route_flow_reuses_contact_info_already_given_in_history():
    # Bug found live 2026-09-19/20: flow_agent used to always repeat the same
    # canned "give me your name/email/phone" text even after the user had
    # already provided it earlier in the conversation. Once there's history,
    # flow_agent must ask the LLM to check it instead of blindly repeating.
    state = _initial_state("mi nombre es Juan, mi correo es juan@test.com y mi telefono es 123")
    history = FakeConversationHistory(
        history=[
            {"role": "assistant", "content": "confirma tus datos"},
        ]
    )
    llm = FakeLLM(
        [
            _tool_call_response("hablar_con_asesor"),
            {"content": "Gracias Juan, derivaremos tu caso a un asesor.", "tool_calls": None},  # flow_agent check
        ]
    )
    graph = _build_graph(llm=llm, check_available=False, conversation_history=history)

    result = await graph.ainvoke(state)

    assert result["route"] == "flow"
    assert result["final_answer"] == "Gracias Juan, derivaremos tu caso a un asesor."


async def test_defaults_to_info_general_when_no_tool_call_returned():
    llm = FakeLLM(
        [
            {"content": "sin tool call", "tool_calls": None},  # orchestrator didn't call classify_intent
            {"content": None, "tool_calls": None},
            {"content": "respuesta", "tool_calls": None},
        ]
    )
    graph = _build_graph(llm=llm)

    result = await graph.ainvoke(_initial_state())

    assert result["route"] == "retrieval"
